did track search clean up
aldmbmtl/Skiff pull request #1
Opened 2021-05-01 20:42 UTC by skeleturtle

Cleaned up the track search, added comments. Yell at me.

2021-05-01 21:35 UTC, b-sea commented on python/skiff/resources/search.py
>  async def album_search(artist_id: int):
Missing a return type hint

2021-05-01 21:36 UTC, b-sea commented on python/skiff/resources/search.py
> +    # 1. request getting all albums
personally, i dont like these kind of comments:

- a comment directly below a docstring, because it feels like you need to breathe a bit and maybe declare some variables or just ease into it.
- commenting every line right after writing what every line will do is redundant and just lengthens the file for no reason

2021-05-01 21:37 UTC, b-sea commented on python/skiff/resources/search.py
> +    futures= []
pep-8 says spaces between `=` unless they are kwargs

2021-05-01 21:43 UTC, b-sea commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
what is the point to this loop? in the end it seems it is just sorted and then the first index is arbitrarily taken. _this_ is where i feel that a detailed comment should be put. all the other comments just re-explain very simple functionality

2021-05-01 21:46 UTC, b-sea commented on python/skiff/resources/search.py
>              future = executor.submit(
whats the reasoning for creating a list of futures and the iterating later vs just building a single array of responses as you go?

2021-05-01 21:47 UTC, b-sea requested changes
See comments

2021-05-01 22:39 UTC, skeleturtle commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
Should I use a triple quote, or a hash tag comment here for a multi line comment?

2021-05-01 22:45 UTC, b-sea commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
its personal preference, but normally i use `#` for these.
```
# So here is a pretty special piece of logic. First you gotta take the bread out of the bag
# THEN put the peanut butter on it. If you do it in the other order, you just end up with
# a peanut butter-ed bag and plain bread. Not fun.
```

2021-05-01 22:47 UTC, b-sea commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
But in addition to that, what *is* the point of that loop? I dont understand what is happening there

2021-05-01 22:56 UTC, skeleturtle commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
each album has multiple releases. Alex want's the original release. Each release has an id, so the assumption is the lowest numbered id would be the original release. Hence the sort and grabbing the first entry in the list.

2021-05-02 00:28 UTC, skeleturtle commented on python/skiff/resources/search.py
>  async def album_search(artist_id: int):
added return type hint, also updated the multi line comment and added the param and return info.

2021-05-02 00:29 UTC, skeleturtle commented on python/skiff/resources/search.py
> +    # 1. request getting all albums
scrubbed out the stupid.

2021-05-02 00:29 UTC, skeleturtle commented on python/skiff/resources/search.py
> +    futures= []
fixed

2021-05-02 00:29 UTC, skeleturtle commented on python/skiff/resources/search.py
> +            release_id = release_ids[0]
added comments, currently leaving as is until further discussion with the boss man on what he wants.

2021-05-02 00:31 UTC, skeleturtle commented on python/skiff/resources/search.py
>              future = executor.submit(
so we added the as_completed(futures) to the for loop to "ensure" threading was happening, but I didn't see a noticeable time increase between that and having just futures.

This code however was 2 seconds faster than my standard for loop. We need to look into the speed issues, and understand this threading.

2021-05-03 03:26 UTC, b-sea commented on python/skiff/resources/search.py
> +async def album_search(artist_id: int) -> list:
id probably declare the type of list in the return type, like the line above
`... -> List[Album]`

2021-05-05 00:44 UTC, closed without merging